import {demoProducts,roleNames,roleDescriptions} from './data.js';
const root=document.querySelector('#app');
const paths={box:'<path d="m21 8-9 5-9-5m9 5v9M3 8l9-5 9 5v9l-9 5-9-5z"/>',check:'<path d="m5 12 4 4L19 6"/>',arrow:'<path d="M5 12h14m-5-5 5 5-5 5"/>',shield:'<path d="m12 3 8 4v5c0 5-8 9-8 9s-8-4-8-9V7z"/><path d="m8 12 3 3 5-6"/>',chart:'<path d="M4 3v17h17M8 16v-5m5 5V7m5 9V4"/>',store:'<path d="M3 10h18l-2-6H5zM5 10v11h14V10M9 21v-7h6v7"/>',users:'<circle cx="9" cy="8" r="3"/><path d="M3 21v-3a6 6 0 0 1 12 0v3m2-16a3 3 0 0 1 0 6m1 4a5 5 0 0 1 3 5"/>',menu:'<path d="M4 6h16M4 12h16M4 18h16"/>',laptop:'<rect x="4" y="3" width="16" height="13" rx="2"/><path d="m4 16-2 4h20l-2-4"/>',phone:'<rect x="7" y="2" width="10" height="20" rx="2"/><path d="M10 18h4"/>',mouse:'<rect x="6" y="2" width="12" height="20" rx="6"/><path d="M12 2v7"/>',monitor:'<rect x="2" y="3" width="20" height="14" rx="2"/><path d="M12 17v4m-5 0h10"/>',headphones:'<path d="M3 14v-3a9 9 0 0 1 18 0v3"/><rect x="2" y="12" width="5" height="9" rx="2"/><rect x="17" y="12" width="5" height="9" rx="2"/>',keyboard:'<rect x="2" y="5" width="20" height="14" rx="2"/><path d="M6 9h.01M10 9h.01M14 9h.01M18 9h.01M6 13h.01M10 13h.01M14 13h.01M18 13h.01M8 16h8"/>',tablet:'<rect x="4" y="2" width="16" height="20" rx="2"/><path d="M10 18h4"/>'};
export const icon=(name)=>`<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[name]||paths.box}</svg>`;
export const brand=()=>`<a class="brand" href="/"><img class="brand-mark" src="/favicon.svg" alt="">TechStore</a>`;
export const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const money=n=>new Intl.NumberFormat('es-PE',{style:'currency',currency:'PEN'}).format(n);
export const status=p=>p.stock===0?'Agotado':p.stock<=p.min?'Stock bajo':'Disponible';
export const badge=p=>`<span class="badge ${p.stock===0?'red':p.stock<=p.min?'amber':'green'}"><i class="dot"></i>${status(p)}</span>`;
const chart=()=>`<svg class="chart-svg" viewBox="0 0 400 120" preserveAspectRatio="none" aria-label="Ejemplo de movimientos de inventario"><path d="M0 100H400M0 65H400M0 30H400" class="grid-line"/><path d="M0 100 55 83 110 88 165 51 220 68 275 31 330 43 400 12V120H0Z" fill="#245bd710"/><path d="M0 100 55 83 110 88 165 51 220 68 275 31 330 43 400 12" class="line-blue"/><path d="M0 110 55 100 110 102 165 85 220 91 275 63 330 76 400 52" class="line-cyan"/></svg>`;
const preview=()=>`<div class="preview"><div class="preview-top"><i></i><i></i><i></i><span>techstore · vista de demostración</span></div><div class="preview-body"><aside class="preview-sidebar">${brand()}${['Dashboard','Productos','Inventario','Tiendas','Reportes'].map((n,i)=>`<div class="preview-nav ${i===0?'active':''}">${icon(['chart','box','box','store','chart'][i])}${n}</div>`).join('')}</aside><div class="preview-content"><div class="preview-title">Tu inventario, bajo control.</div><div class="preview-sub">Una visión clara de todas tus tiendas.</div><div class="preview-stats">${[['Inventario total','12,480','productos'],['Stock bajo','24','por reponer'],['Tiendas activas','4','conectadas']].map(x=>`<div class="preview-stat"><span>${x[0]}</span><b>${x[1]}</b><em>${x[2]}</em></div>`).join('')}</div><div class="preview-chart"><b>Movimientos de inventario</b>${chart()}</div>${[demoProducts[0],demoProducts[2],demoProducts[1]].map(p=>`<div class="preview-row"><span>${p.name}</span>${badge(p)}</div>`).join('')}</div></div></div>`;
const productTable=()=>`<div class="landing-table table-scroll"><table><thead><tr>${['Producto','SKU','Categoría','Tienda','Stock','Precio','Estado'].map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${demoProducts.slice(0,5).map(p=>`<tr><td><div class="product-cell"><div class="product-image ${p.type}">${icon(p.type)}</div><div><strong>${p.name}</strong><small>${p.brand}</small></div></div></td><td class="mono">${p.sku}</td><td>${p.category}</td><td>${p.store}</td><td>${p.stock}</td><td>${money(p.price)}</td><td>${badge(p)}</td></tr>`).join('')}</tbody></table></div>`;
export function landing(){root.innerHTML=`
<nav class="navbar"><div class="container nav-inner">${brand()}<div class="nav-links" id="nav-links"><a href="#inicio">Inicio</a><a href="#features">Características</a><a href="#security">Seguridad</a><a href="#roles">Roles</a><a href="#platform">Plataforma</a></div><div class="nav-actions"><a class="btn ghost" href="/login">Iniciar sesión</a><a class="btn primary" href="/register">Comenzar ${icon('arrow')}</a><button class="icon-btn mobile-toggle" id="nav-toggle" aria-label="Abrir menú" aria-expanded="false">${icon('menu')}</button></div></div></nav>
<main id="main"><section class="hero" id="inicio"><div class="container hero-inner"><div class="hero-copy"><div class="hero-badge"><i class="dot"></i>Gestión inteligente de inventario</div><h1>Control total de tu inventario.<br><span>En todas tus tiendas.</span></h1><p>Centraliza productos, stock y operaciones en una plataforma diseñada para gestionar inventario de forma rápida, clara y segura.</p><div class="hero-actions"><a class="btn primary large" href="/dashboard?demo=1">Explorar plataforma ${icon('arrow')}</a><a class="btn secondary large" href="/login">Iniciar sesión</a></div><div class="hero-checks">${['Stock en tiempo real','Acceso por roles','Seguridad MFA','Reportes claros'].map(x=>`<span>${icon('check')}${x}</span>`).join('')}</div></div><div class="hero-visual">${preview()}<div class="float-chip top">${icon('check')}Stock actualizado</div><div class="float-chip bottom">${icon('box')}+24 unidades</div><div class="float-chip side">${icon('shield')}MFA activo</div><p class="demo-caption">Vista ilustrativa · Datos de demostración</p></div></div></section>
<section class="metrics"><div class="container metrics-inner">${[['12,480','Productos gestionados'],['4','Tiendas conectadas'],['24/7','Control de inventario'],['100%','Gestión centralizada']].map(x=>`<div class="metric"><b>${x[0]}</b><span>${x[1]}</span><small>Escenario de demostración</small></div>`).join('')}</div></section>
<section class="section" id="features"><div class="container"><div class="section-head"><div class="eyebrow">Menos fricción. Más control.</div><h2>Todo tu inventario<br>en un solo lugar.</h2><p>De la primera entrada al último reporte. Una experiencia sencilla para que tu equipo se concentre en lo que importa.</p></div><div class="features-grid"><article class="feature large"><div class="feature-icon">${icon('box')}</div><h3>Control de inventario</h3><p>Conoce qué tienes, dónde está y cuándo necesitas reponer. Cada unidad, a un vistazo.</p><div class="feature-drawing">${demoProducts.slice(0,3).map(p=>`<div class="feature-drawing-row">${icon(p.type)}<span>${p.name}</span><b>${p.stock} uds.</b></div>`).join('')}</div></article>${[['store','Gestión multi-tienda','Cada ubicación conectada a una misma visión.'],['users','Usuarios y roles','El acceso adecuado para cada responsabilidad.'],['chart','Reportes que ayudan','Convierte tus datos en decisiones de reposición.'],['shield','Seguridad integrada','Verifica cada acceso con un segundo factor.']].map(x=>`<article class="feature"><div class="feature-icon">${icon(x[0])}</div><h3>${x[1]}</h3><p>${x[2]}</p></article>`).join('')}<article class="feature wide"><div class="feature-icon">${icon('check')}</div><div><h3>Trazabilidad para tu equipo</h3><p>Explora cómo se presentan los movimientos y la auditoría en la demo de la plataforma.</p></div></article></div></div></section>
<section class="section showcase" id="platform"><div class="container"><div class="section-head center"><div class="eyebrow">Tu operación, en perspectiva</div><h2>Información clara para<br>tomar mejores decisiones.</h2><p>Un catálogo organizado. Estados visibles. Toda la información que necesitas para actuar con confianza.</p></div><div class="showcase-window"><div class="showcase-toolbar"><div><h3>Catálogo de productos</h3><p>Una muestra de tu próximo espacio de trabajo</p></div><a class="btn secondary small" href="/products?demo=1">Explorar demo ${icon('arrow')}</a></div>${productTable()}</div><p class="demo-caption">Los productos y valores de esta sección son ejemplos.</p></div></section>
<section class="section" id="security"><div class="container security-grid"><div><div class="section-head"><div class="eyebrow">Confianza desde el primer acceso</div><h2>Seguridad integrada<br>en cada acceso.</h2><p>Una experiencia protegida, sin añadir complejidad a tu día. Tu equipo entra con confianza y trabaja con los permisos adecuados.</p></div><div class="security-list">${[['shield','Autenticación MFA'],['users','Acceso según rol'],['check','Inicio con Google'],['check','Inicio con GitHub'],['shield','Protección ante intentos fallidos']].map(x=>`<div>${icon(x[0])}${x[1]}</div>`).join('')}</div></div><div class="security-visual"><div class="security-shield">${icon('shield')}</div><div class="security-card"><h3>Centro de seguridad <span class="badge green">Protegido</span></h3><div class="security-line"><span>Autenticación MFA</span><span class="badge green">Activo</span></div><div class="security-line"><span>Sesión</span><strong>Verificada</strong></div><div class="security-line"><span>Último acceso</span><strong>Hoy, 10:42</strong></div><div class="security-line"><span>Dispositivo</span><strong>Chrome · Windows</strong></div></div><p class="demo-caption">Ejemplo visual del estado de seguridad</p></div></div></section>
<section class="section role-section" id="roles"><div class="container"><div class="section-head"><div class="eyebrow">Un equipo. Distintas responsabilidades.</div><h2>Cada persona, con el acceso correcto.</h2><p>La claridad también empieza por saber quién puede hacer qué.</p></div><div class="role-layout"><div class="role-tabs" role="tablist" aria-label="Perfiles">${Object.entries(roleNames).map(([id,name],i)=>`<button class="role-tab" role="tab" data-role="${id}" aria-selected="${i===0}" aria-controls="role-content">${name}${icon('arrow')}</button>`).join('')}</div><div class="role-content" id="role-content" role="tabpanel"></div></div></div></section>
<section class="section"><div class="container reports-promo"><div class="report-visual"><div class="flex between"><h3>Valor del inventario</h3><span class="badge gray">Demo</span></div><span class="report-value">S/ 184,520.00</span>${[['Laptops',78],['Smartphones',58],['Accesorios',36],['Audio',22]].map(x=>`<div class="bar-row"><span>${x[0]}</span><div class="bar-track"><div class="bar-fill" style="width:${x[1]}%"></div></div><b>${x[1]}%</b></div>`).join('')}<p class="note">Distribución ilustrativa por categoría.</p></div><div class="section-head"><div class="eyebrow">De los números a las decisiones</div><h2>Reportes que cuentan<br>la historia completa.</h2><p>Identifica productos críticos, compara tiendas y consulta el valor de tu inventario. Exporta la información para seguir trabajando con tu equipo.</p><a class="text-link" href="/reports?demo=1" style="margin-top:22px">Explorar reportes ${icon('arrow')}</a></div></div></section>
<div class="container cta-wrap"><section class="cta"><div><h2>Gestiona tu inventario con claridad, rapidez y seguridad.</h2><p>Una mejor forma de organizar la tecnología que conecta a tus clientes.</p></div><div class="cta-actions"><a class="btn primary large" href="/login">Acceder a TechStore ${icon('arrow')}</a><a class="btn ghost" href="#features">Conocer funcionalidades</a></div></section></div></main>
<footer class="footer"><div class="container"><div class="footer-grid"><div class="footer-brand">${brand()}<p>Claridad para tu inventario.<br>Control para cada tienda.</p></div><div class="footer-col"><h4>Producto</h4><a href="/inventory?demo=1">Inventario</a><a href="/reports?demo=1">Reportes</a><a href="#security">Seguridad</a></div><div class="footer-col"><h4>Plataforma</h4><a href="/login">Iniciar sesión</a><a href="/register">Crear cuenta</a><a href="/dashboard?demo=1">Explorar demo</a></div><div class="footer-col"><h4>Proyecto</h4><a href="#features">Acerca de</a><button class="text-link" id="privacy" style="background:none;border:0;padding:0;font-weight:500">Privacidad</button></div></div><div class="footer-bottom"><span>TechStore — Proyecto académico.</span><span>Diseñado para una operación más clara.</span></div></div></footer>`;
 const setRole=id=>{document.querySelector('#role-content').innerHTML=`<div class="feature-icon">${icon('users')}</div><h3>${roleNames[id]}</h3><p>Permisos alineados con las responsabilidades de tu equipo.</p><div class="role-permissions">${roleDescriptions[id].map(x=>`<span>${icon('check')}${x}</span>`).join('')}</div>`;document.querySelectorAll('[data-role]').forEach(b=>b.setAttribute('aria-selected',b.dataset.role===id));};setRole('admin');document.querySelectorAll('[data-role]').forEach(b=>b.onclick=()=>setRole(b.dataset.role));
 document.querySelector('#nav-toggle').onclick=e=>{const open=document.querySelector('#nav-links').classList.toggle('mobile-open');e.currentTarget.setAttribute('aria-expanded',open);};
 document.querySelectorAll('#nav-links a').forEach(a=>a.onclick=()=>{document.querySelector('#nav-links').classList.remove('mobile-open');document.querySelector('#nav-toggle').setAttribute('aria-expanded','false');});
 document.querySelector('#privacy').onclick=()=>showInfo('Privacidad','TechStore es un proyecto académico local. El registro almacena tu nombre, email, tienda y contraseña derivada en la base local. Las cuentas Google y GitHub requieren autorización del proveedor. Los datos de la demo son ficticios.');
}
export function showInfo(title,text){document.querySelector('#modal-root').innerHTML=`<div class="modal-overlay"><section class="modal compact" role="dialog" aria-modal="true" aria-label="${esc(title)}"><div class="modal-head"><h2>${esc(title)}</h2><button class="icon-btn" id="close-info" aria-label="Cerrar">×</button></div><div class="modal-body"><p>${esc(text)}</p></div></section></div>`;document.querySelector('#close-info').onclick=()=>document.querySelector('#modal-root').replaceChildren();document.querySelector('#close-info').focus();}
window.addEventListener('scroll',()=>document.querySelector('.navbar')?.classList.toggle('scrolled',scrollY>15),{passive:true});
if(location.pathname==='/'&&!location.hash.startsWith('#mfa='))landing();
else import('./screens.js').then(m=>m.render()).catch(()=>{root.innerHTML=`<main class="container section" id="main">${brand()}<h1 style="margin:30px 0 15px">Estamos preparando tu espacio.</h1><p>La siguiente parte añade la autenticación y la plataforma.</p><a class="btn primary" href="/" style="margin-top:25px">Ver página principal</a></main>`;});
