// Datos de demostración separados de las vistas. Nunca sustituyen datos del servidor.
export const demoStores=[{id:1,name:'Miraflores',address:'Av. Larco 640, Lima',manager:'Valeria Torres'},{id:2,name:'San Isidro',address:'Av. Conquistadores 315, Lima',manager:'Diego Mendoza'},{id:3,name:'Surco',address:'Av. Primavera 1200, Lima',manager:'Camila Ríos'},{id:4,name:'Arequipa',address:'Av. Ejército 793, Arequipa',manager:'Marco Salas'}];
export const demoProducts=[
 {id:1,name:'MacBook Air M3',sku:'TS-LAP-001',brand:'Apple',category:'Laptops',store:'Miraflores',stock:3,min:5,price:4299,description:'Ligera, potente y lista para trabajar. Pantalla Liquid Retina de 13 pulgadas, chip M3 y 256 GB SSD.',type:'laptop'},
 {id:2,name:'Logitech MX Master 3S',sku:'TS-MOU-014',brand:'Logitech',category:'Accesorios',store:'San Isidro',stock:28,min:8,price:429,description:'Mouse inalámbrico con sensor de 8.000 DPI y desplazamiento MagSpeed.',type:'mouse'},
 {id:3,name:'Samsung Galaxy S24',sku:'TS-PHO-008',brand:'Samsung',category:'Smartphones',store:'Surco',stock:16,min:5,price:3299,description:'Pantalla AMOLED de 6,2 pulgadas, cámara de 50 MP y 256 GB de almacenamiento.',type:'phone'},
 {id:4,name:'LG UltraGear 27″',sku:'TS-MON-021',brand:'LG',category:'Monitores',store:'Miraflores',stock:12,min:4,price:1499,description:'Monitor QHD de 27 pulgadas con panel IPS y frecuencia de 165 Hz.',type:'monitor'},
 {id:5,name:'Sony WH-1000XM5',sku:'TS-AUD-017',brand:'Sony',category:'Audio',store:'Arequipa',stock:2,min:5,price:1399,description:'Audífonos inalámbricos con cancelación de ruido y hasta 30 horas de autonomía.',type:'headphones'},
 {id:6,name:'Logitech MX Keys',sku:'TS-KEY-022',brand:'Logitech',category:'Accesorios',store:'Miraflores',stock:0,min:6,price:499,description:'Teclado inalámbrico de perfil bajo con iluminación inteligente.',type:'keyboard'},
 {id:7,name:'iPad Air M2',sku:'TS-TAB-003',brand:'Apple',category:'Tablets',store:'San Isidro',stock:18,min:5,price:2799,description:'Pantalla de 11 pulgadas, chip M2 y conectividad Wi-Fi.',type:'tablet'},
 {id:8,name:'Dell XPS 13',sku:'TS-LAP-009',brand:'Dell',category:'Laptops',store:'Arequipa',stock:9,min:3,price:5499,description:'Laptop de 13 pulgadas para productividad, con 16 GB de RAM.',type:'laptop'}];
export const demoUsers=[{id:1,name:'Rony Bellido',email:'rony@techstore.demo',role:'admin',store:'Miraflores',status:'Activo',last:'Hoy, 10:42'},{id:2,name:'Valeria Torres',email:'valeria@techstore.demo',role:'manager',store:'Miraflores',status:'Activo',last:'Hoy, 10:35'},{id:3,name:'Diego Mendoza',email:'diego@techstore.demo',role:'manager',store:'San Isidro',status:'Activo',last:'Hoy, 09:58'},{id:4,name:'Camila Ríos',email:'camila@techstore.demo',role:'employee',store:'Surco',status:'Activo',last:'Hoy, 09:40'},{id:5,name:'Marco Salas',email:'marco@techstore.demo',role:'employee',store:'Arequipa',status:'Bloqueado',last:'Ayer, 16:20'},{id:6,name:'Lucía Paredes',email:'lucia@techstore.demo',role:'auditor',store:'Miraflores',status:'Activo',last:'Hoy, 08:30'},{id:7,name:'Andrés Vega',email:'andres@techstore.demo',role:'employee',store:'San Isidro',status:'Pendiente',last:'Sin accesos'}];
export const demoMovements=[{id:1,product:1,type:'Entrada',quantity:12,store:'Miraflores',reason:'Reposición de proveedor',user:'Valeria Torres',date:'2026-10-07T10:35:00'},{id:2,product:3,type:'Salida',quantity:4,store:'Surco',reason:'Venta en tienda',user:'Camila Ríos',date:'2026-10-07T10:20:00'},{id:3,product:2,type:'Entrada',quantity:24,store:'San Isidro',reason:'Recepción de mercadería',user:'Diego Mendoza',date:'2026-10-07T09:58:00'},{id:4,product:5,type:'Ajuste',quantity:2,store:'Arequipa',reason:'Conteo de inventario',user:'Rony Bellido',date:'2026-10-06T16:42:00'}];
export const demoAudit=[{id:1,date:'2026-10-07T10:42:00',user:'Rony Bellido',action:'LOGIN_SUCCESS',resource:'Sesión · MFA verificado',result:'Correcto'},{id:2,date:'2026-10-07T10:35:00',user:'Valeria Torres',action:'STOCK_ADJUSTMENT',resource:'MacBook Air M3',result:'Correcto'},{id:3,date:'2026-10-07T10:28:00',user:'Rony Bellido',action:'UPDATE_PRODUCT',resource:'LG UltraGear 27″',result:'Correcto'},{id:4,date:'2026-10-07T10:20:00',user:'Camila Ríos',action:'STOCK_ADJUSTMENT',resource:'Samsung Galaxy S24',result:'Correcto'},{id:5,date:'2026-10-06T16:20:00',user:'Marco Salas',action:'USER_BLOCKED',resource:'5 intentos fallidos',result:'Bloqueado'}];
export const demoNotifications=[{title:'3 productos necesitan atención',body:'Revisa el stock bajo antes de la próxima reposición.',path:'/inventory'},{title:'Recepción de mercadería',body:'24 unidades añadidas en San Isidro.',path:'/movements'}];
export const series={7:{labels:['Jue','Vie','Sáb','Dom','Lun','Mar','Mié'],incoming:[24,40,34,48,37,64,58],outgoing:[18,25,24,30,22,43,38]},30:{labels:['Sem. 1','Sem. 2','Sem. 3','Sem. 4'],incoming:[35,62,45,74],outgoing:[25,38,30,55]},90:{labels:['Jul','Ago','Sep','Oct'],incoming:[44,60,51,76],outgoing:[26,42,35,56]}};
export const roleNames={admin:'Administrador',manager:'Gerente de tienda',employee:'Empleado de ventas',auditor:'Auditor'};
export const roleDescriptions={admin:['Gestionar usuarios y roles','Gestionar productos y precios','Consultar todas las tiendas','Ver y exportar reportes'],manager:['Gestionar productos de su tienda','Consultar reportes de su ubicación','Controlar el stock de su tienda'],employee:['Consultar productos','Actualizar stock de su tienda','Sin permisos para modificar precios'],auditor:['Consultar información de todas las tiendas','Generar y exportar reportes','Sin permisos de modificación']};
