"""SQLite local y PostgreSQL persistente, con transacciones por operación."""
import os
import sqlite3
from contextlib import contextmanager

class ConfigurationError(RuntimeError):
    pass

class Record(dict):
    def __getitem__(self, key):
        return list(self.values())[key] if isinstance(key, int) else super().__getitem__(key)

def record_factory(cursor):
    names = [column.name for column in cursor.description] if cursor.description else []
    return lambda values: Record(zip(names, values))

def is_integrity_error(error):
    if isinstance(error, sqlite3.IntegrityError):
        return True
    # No es necesario importar el driver PostgreSQL al ejecutar localmente.
    return getattr(error, 'sqlstate', None) in ('23505', '23503', '23514', '23502')

class Database:
    def __init__(self, raw, postgres):
        self.raw, self.postgres = raw, postgres

    def execute(self, sql, parameters=(), for_update=False):
        if self.postgres:
            sql = sql.replace('?', '%s')
            if for_update:
                sql += ' FOR UPDATE'
        return self.raw.execute(sql, parameters)

    def executemany(self, sql, parameters):
        cursor = self.raw.cursor()
        cursor.executemany(sql.replace('?', '%s') if self.postgres else sql, parameters)
        return cursor

    def executescript(self, schema):
        if self.postgres:
            schema = schema.replace('id INTEGER PRIMARY KEY', 'id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY')
            schema = schema.replace(' REAL', ' DOUBLE PRECISION')
        for statement in schema.split(';'):
            if statement.strip():
                self.execute(statement)

@contextmanager
def connect(local_path):
    url = os.getenv('DATABASE_URL') or os.getenv('POSTGRES_URL')
    postgres = bool(url)
    if postgres:
        if not url.startswith(('postgres://', 'postgresql://')):
            raise ConfigurationError('DATABASE_URL debe ser una conexión PostgreSQL.')
        try:
            import psycopg
        except ImportError as error:
            raise ConfigurationError('Instala las dependencias con pip install -r requirements.txt.') from error
        raw = psycopg.connect(url, row_factory=record_factory, connect_timeout=10)
    else:
        if os.getenv('VERCEL'):
            raise ConfigurationError('Conecta PostgreSQL en Vercel y configura DATABASE_URL. No se guardarán usuarios en archivos temporales.')
        raw = sqlite3.connect(local_path, timeout=15)
        raw.row_factory = sqlite3.Row
        raw.execute('PRAGMA busy_timeout=15000')
        raw.execute('BEGIN IMMEDIATE')
    try:
        yield Database(raw, postgres)
        raw.commit()
    except BaseException:
        raw.rollback()
        raise
    finally:
        raw.close()
